// Copyright © 2025 Apple Inc.

import Foundation

/// Parser for Gemma format: call:name{key:value,k:<escape>str<escape>}
/// Reference: https://github.com/ml-explore/mlx-lm/blob/main/mlx_lm/tool_parsers/function_gemma.py
public struct GemmaFunctionParser: ToolCallParser, Sendable {
    public let startTag: String?
    public let endTag: String?
    public let escapeMarker: String?

    public init(startTag: String, endTag: String, escapeMarker: String) {
        self.startTag = startTag
        self.endTag = endTag
        self.escapeMarker = escapeMarker
    }

    public func parse(content: String, tools: [[String: any Sendable]]?) -> ToolCall? {
        // Unwrap
        guard let start = startTag, let end = endTag else { return nil }
        guard let marker = escapeMarker else { return nil }

        // Strip tags if present
        var text = content
        if let startRange = text.range(of: start) {
            text = String(text[startRange.upperBound...])
        }
        if let endRange = text.range(of: end) {
            text = String(text[..<endRange.lowerBound])
        }

        // Pattern: call:(\w+)\{(.*?)\}
        // Find "call:" followed by function name and arguments in braces
        guard let callRange = text.range(of: "call:") else { return nil }

        let remaining = String(text[callRange.upperBound...])

        // Extract function name (word characters until {)
        guard let braceStart = remaining.firstIndex(of: "{") else { return nil }
        let funcName = String(remaining[..<braceStart])

        guard !funcName.isEmpty else { return nil }

        // Extract arguments string (everything between { and })
        guard let braceEnd = remaining.lastIndex(of: "}") else { return nil }
        var argsStr = String(remaining[remaining.index(after: braceStart) ..< braceEnd])

        var arguments: [String: any Sendable] = [:]

        // Parse key:value pairs
        while !argsStr.isEmpty {
            // Find the key (everything before :)
            guard let colonIdx = argsStr.firstIndex(of: ":") else { break }
            let key = String(argsStr[..<colonIdx])
            argsStr = String(argsStr[argsStr.index(after: colonIdx)...])

            // Handle escaped strings
            if argsStr.hasPrefix(marker) {
                argsStr = String(argsStr.dropFirst(marker.count))
                guard let endEscape = argsStr.range(of: marker) else { break }
                let value = String(argsStr[..<endEscape.lowerBound])
                arguments[key] = convertParameterValue(
                    value, paramName: key, funcName: funcName, tools: tools)
                argsStr = String(argsStr[endEscape.upperBound...])
                // Skip comma if present
                if argsStr.hasPrefix(",") {
                    argsStr = String(argsStr.dropFirst())
                }
                continue
            }

            // Handle regular values until a top-level comma. Composite JSON
            // arguments may contain their own commas; splitting at the first
            // byte corrupts objects and arrays generated by the schema grammar.
            let commaIdx = topLevelComma(in: argsStr) ?? argsStr.endIndex
            let value = String(argsStr[..<commaIdx])
            argsStr =
                commaIdx < argsStr.endIndex
                ? String(argsStr[argsStr.index(after: commaIdx)...]) : ""

            // Try JSON decode, fallback to string
            if getParameterType(funcName: funcName, paramName: key, tools: tools) != nil {
                arguments[key] = convertParameterValue(
                    value, paramName: key, funcName: funcName, tools: tools)
            } else if let data = value.data(using: .utf8),
                let json = deserializeJSON(data)
            {
                arguments[key] = json
            } else {
                arguments[key] = value
            }
        }

        return ToolCall(function: .init(name: funcName, arguments: arguments))
    }

    private func topLevelComma(in text: String) -> String.Index? {
        var objectDepth = 0
        var arrayDepth = 0
        var quote: Character?
        var escaped = false

        for index in text.indices {
            let character = text[index]
            if let activeQuote = quote {
                if escaped {
                    escaped = false
                } else if character == "\\" {
                    escaped = true
                } else if character == activeQuote {
                    quote = nil
                }
                continue
            }
            switch character {
            case "\"", "'": quote = character
            case "{": objectDepth += 1
            case "}": objectDepth = max(0, objectDepth - 1)
            case "[": arrayDepth += 1
            case "]": arrayDepth = max(0, arrayDepth - 1)
            case "," where objectDepth == 0 && arrayDepth == 0:
                return index
            default: break
            }
        }
        return nil
    }
}
